teleop_twist_joy_node:
  ros__parameters:
    axis_linear:
      x: 1
    scale_linear:
      x: 0.15
    scale_linear_turbo:
      x: 0.3

    axis_angular:
      yaw: 2
    scale_angular:
      yaw: 0.6

    enable_button: 8  # L2 shoulder button
    enable_turbo_button: 9  # L1 shoulder button